name: Gradle CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Setup Java
    - name: Setup JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Checkout Code
      uses: actions/checkout@v2
      
    # Make Gradle wrapper executable
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    # Run build using Gradle
    - name: Build with Gradle
      run: ./gradlew build

    # Uploading artifact to be reused within the test job
    - uses: actions/upload-artifact@main
      with:
        name: Gradle artifact
        path: ./gradlew

  test:
    # Set this job to only run after the build job
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Setup Java
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Checkout code
        uses: actions/checkout@v2

      # Make Gradle wrapper executable
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Run tests using Gradle
      - name: Run tests with Gradle
        run: ./gradlew test --stacktrace -i
