name: CI with Java and Gradle

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    # Setup Jave
    - name: Setup JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Checkout Code
      uses: actions/checkout@v2
      
    # Make Gradle wrapper executable
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    # Run build using Gradle
    - name: Build with Gradle
      run: ./gradlew build
      
